let g:syntastic_quiet_messages = {}
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1 
let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol = "⚠"
let g:syntastic_auto_loc_list = 1
let g:syntastic_ruby_checkers = ['mri', 'rubocop']
let g:syntastic_ruby_mri_exec = '~/.rvm/rubies/ruby-2.4.0/bin/ruby'
let g:syntastic_ruby_rubocop_exec = '~/.rvm/gems/ruby-2.4.0/bin/rubocop'
let g:syntastic_typescript_checkers=['tslint']
let g:syntastic_javascript_checkers = ['jshint']
