eval "$(starship init bash)"
export CLICOLOR=1

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# BASH
export HISTFILE="$XDG_DATA_HOME"/bash/history 

# READLINE
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc

# Less
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history

# VIM init
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# Docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker 

# Cargo
export CARGO_HOME="$XDG_DATA_HOME"/cargo 

# Rustup
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup 

# RubyGems
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem

# Bundler
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle/config
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle

# PostgresSQL
export PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
export PSQL_HISTORY="$XDG_CACHE_HOME/pg/psql_history"
export PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"

# TMUX init session
tmux has-session -t development
if [ $? != 0  ]
then
    tmux new-session -s development
fi
tmux attach -t development  

